name: Create card

on:
  workflow_dispatch:
    inputs:
      title:
        description: "Card title"
        required: true
        type: string
      body:
        description: "Card description"
        required: false
        default: ""
        type: string

permissions:
  contents: read
  issues: write

jobs:
  create-card:
    runs-on: ubuntu-latest

    steps:
      - name: Debug inputs
        run: |
          echo "title=[${{ inputs.title }}]"
          echo "body=[${{ inputs.body }}]"

      - name: Create card
        id: create_issue
        uses: technote-space/create-project-card-action@v1
        env:
          ISSUE_TITLE: ${{ inputs.title }}
          ISSUE_BODY: ${{ inputs.body }}
        with:
          PROJECT: FAIRification
          COLUMN: Todo
